services:
  bot:
    build: .
    container_name: personal-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./ubt_course.db:/app/ubt_course.db
      - ./bot_data.db:/app/bot_data.db
